version: '3.9'

services:
#############################################################
#                  NATS Deployment                          #
#############################################################
    nats-solintecno:
        image: docker.uclv.cu/nats
        container_name: nats-solintecno
        ports:
            - "8222:8222"
            - "${PORT}:4222"
        command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
        networks: [ "nats_solintecno_network" ]
    nats-solintecno-1:
        image: docker.uclv.cu/nats
        command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats_solintecno_network://ruser:T0pS3cr3t@nats:6222"
        networks: [ "nats_solintecno_network" ]
        depends_on: [ "nats-solintecno" ]
    nats-solintecno-2:
        image: docker.uclv.cu/nats
        command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats_solintecno_network://ruser:T0pS3cr3t@nats:6222"
        networks: [ "nats_solintecno_network" ]
        depends_on: [ "nats-solintecno" ]

networks:
    nats_solintecno_network:
        name: nats_solintecno_network
