version: '3.7'

services:
  camel-cocoon:
      container_name: camel-cocoon
      image: camel-cocoon:0.1.0 
      build: 
        context: . 
        target: develop
      ports:
        - 9887:8080
      tty: true
      working_dir: /camel
      volumes:
        - ./:/camel
     
volumes:
  local:
    
    