version: '3.7'

services:
  ms-security:
        container_name: ms-security
        image: ms-security:1.0.0
        build: .
        ports:
            - 3004:3000
        tty: true
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules

