version: '3.9'

services:
#############################################################
#                       MongoDB                             #
#                                                           #
#  Access to http://localhost:8081/ to manage the databases #
#############################################################
    mongo:
        image: docker.uclv.cu/mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: interview
        ports:
        - 27018:27017
        - 9229:9229
        volumes:
         - ./docker-entrypoint-initdb2.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks: [ "mongodb_network" ]

    #mongo-express:
    #    image: mongo-express
    #    restart: always
    #    ports:
    #    - 8081:8081
    #    environment:
    #        ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    #        ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    #    networks: [ "mongodb_network" ]

volumes:
    dbdata2:
networks:
    mongodb_network:
        name: mongodb_network